- name: Copy file with db data to server
  copy:
    src: "{{ target_file }}"
    dest: "{{ appdir }}/{{ target_file | basename }}"
    owner: "{{ userdba }}"
    group: "{{ userdba }}"
    mode: u=rw,g=,o=

- name: Restore db data
  postgresql_db:
    name: "{{ db }}"
    state: restore
    target: "{{ appdir }}/{{ target_file | basename }}"
    login_host: "/var/run/postgresql"
    login_user: postgres
  become: yes
  become_user: postgres
  become_method: sudo
  register: var
  failed_when: "var.stderr_lines | length > 0"
